org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true
# compileSdk 37 比 AGP 9.2.1 的默认支持级别新，需显式放行（Miuix 官方工程同样这么做）
android.suppressUnsupportedCompileSdk=37

# Kotlin
kotlin.code.style=official
